### ISSUE TITLE
Check for correct order of heading tags

### ISSUE THREAD

**Issue by SavvasStephanides** [jackdomleo7/Checka11y.css#13]
Headings should be in the correct order [See here for more information](https://www.w3.org/WAI/tutorials/page-structure/headings/). 

> Skipping heading ranks can be confusing and should be avoided where possible

For example, this is correct:

```html
<h1>This is a heading</h1>
<h2>This is a subheading</h2>
```

This is incorrect because it goes from `h1` straight to `h3` (skipping `h2`):

```html
<h1>This is a heading</h1>
<h3>This is an h3 heading</h3>
```

Not completely sure how this can be done with `CSS`. I have tried this

```css
h1+h3,
h1+h4 {
    border: var(--checka11y-error-border-width, 5px) solid var(--checka11y-error-color, red) !important;
}
```

which checks if an `h1` heading is followed by an `h3` or `h4` header. However, this doesn't take into account elements in between the headers. Any ideas welcome.
