### ISSUE TITLE
Check a lang attribute exists in the <html> tag

### ISSUE THREAD

**Issue by SavvasStephanides** [jackdomleo7/Checka11y.css#3]
A `lang` attribute should exist in the `<html>` tag, which signifies to the screen reader what language the page is in.

Evidence: https://www.w3.org/WAI/standards-guidelines/act/rules/html-page-lang-b5c3f8/

**Comment by jackdomleo7** [comment]
Do we need to refactor this feature to check for empty `lang` attributes too? I.e. `lang=""`.

**Comment by danspratling** [comment]
@jackdomleo7 I think so. I'm pretty sure CSS equates `lang` and `lang=""` to `lang=true` which means that an empty lang check would technically pass, even though that's invalid.

**Comment by jackdomleo7** [comment]
Ok, awesome, we'll leave this as re-opened so it can be added to.

**Proposed solution**

```css
html:not( [lang] ) body,
html[lang=""] body {
  ...
}

html:not( [lang] ) body::before,
html[lang=""] body::before {
  ...
}
```
