### ISSUE TITLE
Images should have a meaningful alternative text

### ISSUE THREAD

**Issue by alvaromontoro** [jackdomleo7/Checka11y.css#35]
### Describe the new a11y feature or project enhancement

Images should nave a descriptive alternative text. Images in which the alternative text is "image" or "graphic" or a " " (blank space), are not providing enough information for assistive technologies.

### Describe the solution you'd like

This one is tricky because it can be really language-dependant. The same word that works in English (image) may work in French (image) but not in Spanish (imagen) or German (bild). Also, images don't have `::before` and `::after` pseudo-elements to display the error.

The language barrier is difficult to skip, the solution could include some common words in different languages that would trigger the rule, but having all of them may be complex. Some of them (e.g., a blank space). As for the highlight, the project could include an inline image in SVG or base64 with a message through the `content` property.

Then the selector/rule could be something like this:

```css
image[alt=" "],
image[alt="image"i],
image[alt="graphic"i],
image[alt="photo"i],
image[alt="picture"i],
... {
  border: 4px solid red;
  content: url(path-to-error-image)
}
```

### Link(s)

- [Codepen with demo of the code working](https://codepen.io/alvaromontoro/pen/WNwqQgj)
- [WebAIM: Alternative text](https://webaim.org/techniques/alttext/)
